# Generated by Django 3.0.4 on 2020-04-25 04:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parents', '0006_auto_20200424_2221'),
        ('babies', '0002_auto_20200424_2214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baby',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='parents.Parent'),
        ),
    ]
